GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "sample",
    "important": "true"
}

###
PUT http://localhost:3001/api/notes/6830d4714c8baac8cd2fd017
Content-Type: application/json

{
    "content": "HTML can be hard",
    "important": "false"
}